# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - '**'
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn lint
    - run: yarn test
    - run: yarn disable:blog

    - uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        commit_user_name: GitHub Actions Bot
        commit_user_email: my-github-actions-bot@example.org
        commit_message: "GitHub Actions Bot Cleaning up dependencies"

        branch: ${{ github.head_ref }}

      env:
        CI: true